DELETE FROM ZONA CASCADE;
DELETE FROM PEDIDO_PRODUCTO CASCADE;
DELETE FROM SOBREMESA CASCADE;
DELETE FROM PORTATILES CASCADE;
DELETE FROM CONSOLA CASCADE;
DELETE FROM DISPOSITIVOS_MOVILES CASCADE;
DELETE FROM PRODUCTO CASCADE;
DELETE FROM ZONA_PRODUCTO CASCADE;
DELETE FROM PEDIDO CASCADE;
DELETE FROM TRABAJA CASCADE;
DELETE FROM LIBRE CASCADE;
DELETE FROM EMPLEADO CASCADE;
DELETE FROM SOCIO CASCADE;
DELETE FROM LOCAL CASCADE;

