-- Deshabilitar restricciones para evitar errores de integridad referencial
SET session_replication_role = 'replica';

-- Eliminar tablas en el orden correcto
DROP TABLE IF EXISTS DISPOSITIVOS_MOVILES CASCADE;
DROP TABLE IF EXISTS CONSOLA CASCADE;
DROP TABLE IF EXISTS PORTATILES CASCADE;
DROP TABLE IF EXISTS SOBREMESA CASCADE;
DROP TABLE IF EXISTS LIBRE CASCADE;
DROP TABLE IF EXISTS PEDIDO_PRODUCTO CASCADE;
DROP TABLE IF EXISTS PEDIDO CASCADE;
DROP TABLE IF EXISTS TRABAJA CASCADE;
DROP TABLE IF EXISTS ZONA_PRODUCTO CASCADE;
DROP TABLE IF EXISTS EMPLEADO CASCADE;
DROP TABLE IF EXISTS SOCIO CASCADE;
DROP TABLE IF EXISTS PRODUCTO CASCADE;
DROP TABLE IF EXISTS ZONA CASCADE;
DROP TABLE IF EXISTS LOCAL CASCADE;

-- Habilitar nuevamente las restricciones
SET session_replication_role = 'origin';
