services:
  web:
    build: .
    ports:
      - 80:5000
    volumes:
      - ./flask_app:/app 
    environment:
      FLASK_APP: app.py  
      FLASK_ENV: development
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: adbd2425
      POSTGRES_DB: flask_db
      DATABASE_URL: postgres://usuario:adbd2425@postgres:5433/flask_db
    depends_on:
      - postgres
    command: >
      sh -c "python init_db.py &&
             flask run --host=0.0.0.0"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: adbd2425
      POSTGRES_DB: flask_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
